# This is a basic workflow to help you get started with Actions
name: Best Practices Check

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - 'main'
      - 'rel-**'
      - 'TS-*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  dev-checks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          echo "SOURCE_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          echo "SOURCE_BRANCH=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
          echo "TARGET_BRANCH=$(echo ${GITHUB_BASE_REF} | tr / -)" >> $GITHUB_ENV
        
      # Check if branch name is according to the guidelines
      - name: Check branch name
        if: ${{ !startsWith(env.SOURCE_BRANCH,'TS-') }}
        run: |
          echo "::debug::Branch name must start with 'TS-' ${{ env.SOURCE_BRANCH }}"
          exit 1
